config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "products#index"
    resources :users
    resources :products
    resources :suggests
    resources :orders
    resources :order_details
    resources :categories
  end
  root "static_pages#home"
  get "search(/:search)" => "searches#index", as: :search
  devise_for :users, controllers: {registrations: "registrations",
    omniauth_callbacks: "users/omniauth_callbacks"}
  resources :products
  resources :carts
  resources :comments
  resources :orders
  resources :categories, only: :show
  resources :users, only: :show
  resources :suggests, only: [:new, :create]
  post '/rate' => 'rater#create', :as => 'rate'
end

app/models/order.rb
class Order < ApplicationRecord
  attr_accessor :cart

  belongs_to :user, dependent: :destroy
  has_many :order_details
  has_many :products, through: :order_details
  enum status: {open: 1, close: 0}
  validates :address, presence: true, length: {maximum: 50}

  after_create :build_order_details

  scope :newest, ->{order created_at: :desc}

  private
  def build_order_details
    cart.items.each do |item|
      order_details.create product_id: item.product_id, quantity: item.quantity
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  layout "admin_template"
  before_action :authenticate_user!
  before_action :verify_admin
  before_action :load_order, only: :update

  def index
    @orders = Order.all.newest
  end

  def update
    if @order.status == "open"
      if @order.update_attribute(:status, "close")
        flash[:success] = t "saved"
        redirect_to admin_orders_path
        respond_to do |format|
          format.html
          format.js
        end
      else
        redirect_to admin_orders_path
      end
    else
      if @order.update_attribute(:status, "open")
        flash[:success] = t "saved"
        redirect_to admin_orders_path
         respond_to do |format|
          format.html
          format.js
        end
      else
        redirect_to admin_orders_path
      end
    end

  end

  private
  # def order_params
  #   params.require(:order).permit :status
  # end

  def load_order
    @order = Order.find_by id: params[:id]
    # binding.pry
    unless @order
      flash[:danger] = t "order_not_exist"
      redirect_to admin_orders_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_order, only: :show

  def index
    @orders = current_user.orders.newest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def create
    if @cart.present?
      @order = Order.new order_params
      if @order.save
        OrderMailer.index(@order, current_user).deliver_later
        Chatwork.send_message @order
        session.delete :cart
        flash[:success] = t "success.orders.successful"
        redirect_to order_path @order
      else
        flash[:danger] = t "danger.orders.address"
        redirect_to :back
      end
    else
      flash[:danger] = t "carts.not_product"
      redirect_to :back
    end
  end

  def show
  end

  private
  def order_params
    params.require(:order).permit(:address).merge! user: current_user,
      total: @cart.total_price, cart: @cart
  end

  def load_order
    @order = Order.find_by id: params[:id]
    unless @order
      flash[:danger] = t "danger.orders.not_found"
      redirect_to root_path
    end
  end
end

app/views/admin/orders/_order.html.erb
<% @orders.each do |order| %>
  <tr>
    <th><%= order.total %></th>
    <th><%= order.user.name %></th>
    <th>
      <%= link_to t("detail"), admin_order_detail_path(order.id),
        class: "btn btn-success btn-sm"  %>
    </th>
    <th>
      <% if order.status == "close" %>
        <%= link_to t("accepted"), admin_order_path(order.id), method: :put, class: "btn btn-success" %>
      <% else %>
        <%= link_to t("accept"), admin_order_path(order.id), method: :put, class: "btn btn-danger" %>
      <% end %>
    </th>
  </tr>
<% end %>

app/views/admin/orders/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="portlet box green">
      <div class="team-heading">
        <h3><%= t "product_list" %></h3>
        <hr>
      </div>
      <div class="portlet-body">
        <table class="table table-striped table-hover table-responsive datatable"
          id="data-list">
          <thead>
            <tr>
              <th><%= t "total" %></th>
              <th><%= t "user" %></th>
              <th></th>
              <th></th>
            </tr>
          </thead >
          <tbody>
            <%= render "order" %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>