config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "products#index"
    resources :users
    resources :products
    resources :suggests
    resources :orders
    resources :order_details
    resources :categories
  end
  root "static_pages#home"
  get "search(/:search)" => "searches#index", as: :search
  devise_for :users, controllers: {registrations: "registrations",
    omniauth_callbacks: "users/omniauth_callbacks"}
  resources :products
  resources :carts
  resources :comments
  resources :orders
  resources :categories, only: :show
  resources :users, only: :show
  resources :suggests, only: [:new, :create]
  post '/rate' => 'rater#create', :as => 'rate'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :comments
  has_many :order_details
  has_many :orders, through: :order_details

  scope :newest, ->{order created_at: :desc}
  scope :limit_item, ->{limit Settings.home.limit_product}
  scope :search, ->search do
    where "LOWER(name) LIKE ?", "%#{search.downcase}%" if search.present?
  end
  scope :search_by_condition, ->category_id do
    where "category_id = ?", category_id if category_id.present?
  end

  mount_uploader :image, PictureUploader

  ratyrate_rateable "rate"
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin_template"
  before_action :authenticate_user!
  before_action :load_product, only: [:destroy, :edit, :update]

  def index
    @categories = Category.active.newest
    @products = Product.search_by_condition(params[:search]).newest
  end

  def new
    @categories = Category.newest
    $product_suggest = Suggest.find_by id: params[:product_suggest]
    if $product_suggest
      @product = Product.new name: $product_suggest.name,
      description: $product_suggest.description,
      image: $product_suggest.image
    else
      @product = Product.new
    end
  end

  def edit
    @categories = Category.newest
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t "saved"
      redirect_to admin_root_path
    else
      render :edit
    end
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t "saved"
      if $product_suggest
        $product_suggest.update_attribute(:status, false)
      end
    else
      flash[:danger] = t "save_not_successfully"
    end
    redirect_to admin_products_path
  end

  def destroy
    if @product.destroy
      flash[:success] = t "delete_successfully"
    else
      flash[:danger] = t "delete_not_successfully"
    end
    redirect_to admin_root_path
  end

  private
  def product_params
    params.require(:product).permit :name, :price, :category_id,
      :quantity, :image, :description
  end

  def load_product
    @product = Product.find_by id: params[:id]
    unless @product
      flash[:danger] = t "product_not_exist"
      redirect_to admin_root_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: :show

  def index
    @products = Product.newest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
    @comments = @product.comments.newest.paginate page: params[:page],
      per_page: Settings.per_page_comment
    @categories = Category.first(Settings.limit_categories)
  end

  private
    def load_product
    @product = Product.find_by id: params[:id]
    unless @product
      flash[:danger] = t "could_not_find_the_product"
      redirect_to root_path
    end
  end
end

app/views/admin/products/_product.html.erb
<% @products.each do |product| %>
  <tr>
    <th><%= product.name %></th>
    <% if !product.image.nil? %>
      <th><%= image_tag product.image %></th>
    <% else %>
      <th><%= t "no_image" %></th>
    <% end %>
    <th><%= product.price %><%= t "currency" %></th>
    <th><%= product.quantity %></th>

    <th>
      <%= link_to edit_admin_product_path(product.id), title: t("edit") do %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
    </th>
    <th>
      <%= link_to t("delete"), admin_product_path(product.id),
        method: :delete, class: "btn btn-danger btn-sm",
        data: {confirm: t("admin.confirm_del")}  %>
    </th>
  </tr>
<% end %>

app/views/admin/products/edit.html.erb
<div class="row">
  <div class="col-md-12 box">
    <div class="portlet green">
      <div class="team-heading">
        <h3><%= t "edit_product" %></h3>
        <hr>
      </div>
      <div class="portlet-body">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for [:admin, @product] do |f| %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control"%>
            </div>
            <div class="form-group">
              <%= f.label :price %>
              <%= f.text_field :price, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :category %>
              <%= f.select "category_id", options_for_select(@categories.collect{
                |category| [category.name, category.id]}),
                class:"selectpicker" %>
            </div>
            <div class="form-group">
              <%= f.label :quantity %>
              <%= f.number_field :quantity, class: "form-control"%>
            </div>
            <div class="form-group">
              <%= f.label :image %>
              <%= f.file_field :image %>
            </div>
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class: "form-control", rows: "5" %>
            </div>
            <div class="text-center">
              <%= f.submit t("edit_product"), class: "btn btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="portlet box green">
      <div class="team-heading">
        <h3>
          <%= t "product_list" %>
          <%= link_to t("add_new"), new_admin_product_path, class: "btn btn-primary" %>
        </h3>
        <hr>
      </div>
      <div class="portlet-body">
        <div class="form-group text-center">
          <%= form_tag admin_products_path, method: "GET", id: "category_search" do %>
            <strong><%= t "category" %></strong>
            <%= hidden_field_tag :search, params[:search], id: "search" %>
            <%= select_tag "category_id", options_from_collection_for_select(@categories, "id", "name"),
              include_blank: t("all"), class: "selectpicker form-control" %>
          <% end %>
        </div>
        <table class="table table-striped table-hover table-responsive datatable" id="data-list">
          <thead>
            <tr>
              <th><%= t "name" %></th>
              <th><%= t "image" %></th>
              <th><%= t "price" %></th>
              <th><%= t "quantity" %></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody id="results">
            <%= render "product" %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.js.erb
$("#results").html('<%= j render "product" %>');

app/views/admin/products/new.html.erb
<div class="row">
  <div class="col-md-12 box">
    <div class="portlet green">
      <div class="team-heading">
        <h3><%= t "create_product" %></h3>
        <hr>
      </div>
      <div class="portlet-body">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for [:admin, @product] do |f| %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control"%>
            </div>
            <div class="form-group">
              <%= f.label :price %>
              <%= f.text_field :price, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :category %>
              <%= f.select "category_id", options_for_select(@categories.collect{
                |category| [category.name, category.id]}),
                class: "btn btn-default filter-categories" %>
            </div>
            <div class="form-group">
              <%= f.label :quantity %>
              <%= f.number_field :quantity, class: "form-control"%>
            </div>
            <div class="form-group">
              <%= f.label :image %>
              <%= f.file_field :image %>
            </div>
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class: "form-control", rows: "5" %>
            </div>
            <div class="text-center">
              <%= f.submit t("create_product"), class: "btn btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>