config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "products#index"
    resources :users
    resources :products
    resources :suggests
    resources :orders
    resources :order_details
    resources :categories
  end
  root "static_pages#home"
  get "search(/:search)" => "searches#index", as: :search
  devise_for :users, controllers: {registrations: "registrations",
    omniauth_callbacks: "users/omniauth_callbacks"}
  resources :products
  resources :carts
  resources :comments
  resources :orders
  resources :categories, only: :show
  resources :users, only: :show
  resources :suggests, only: [:new, :create]
  post '/rate' => 'rater#create', :as => 'rate'
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  belongs_to :user

  mount_uploader :image, PictureUploader

  scope :newest, ->{order created_at: :desc}
  validates :name, presence: true, length: {maximum: 50}
  validates :user, presence: true
end

app/controllers/admin/suggests_controller.rb
class Admin::SuggestsController < ApplicationController
  layout "admin_template"
  before_action :authenticate_user!
  before_action :verify_admin
  before_action :load_suggest, only: :destroy

  def index
    @suggests = Suggest.newest
  end

  def destroy
    if @suggest.destroy
      flash[:success] = t "delete_successfully"
    else
      flash[:danger] = t "delete_not_successfully"
    end
    redirect_to admin_suggests_path
  end

  def load_suggest
    @suggest = Suggest.find_by id: params[:id]
    unless @suggest
      flash[:danger] = t "suggest_not_exist"
      redirect_to admin_suggests_path
    end
  end
end

app/controllers/suggests_controller.rb
class SuggestsController < ApplicationController
  layout "signup_template"
  before_action :authenticate_user!

  def new
    @suggest = Suggest.new
  end

  def create
    @suggest = Suggest.new product_suggest_params
    @suggest.user_id = current_user.id
    if @suggest.save
      flash[:success] = t "success.suggests.successful"
      redirect_to root_path
    else
      flash[:danger] = t "danger.suggests.fails"
      render :new
    end
  end

  private
  def product_suggest_params
    params.require(:suggest).permit :name, :image, :description
  end
end

app/views/admin/suggests/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="portlet box green">
      <div class="team-heading">
        <h3><%= t "suggest_list" %></h3>
        <hr>
      </div>
      <div class="portlet-body">
        <table class="table table-striped table-hover table-responsive datatable"
          id="data-list">
          <thead>
            <tr>
              <th><%= t "name" %></th>
              <th><%= t "image" %></th>
              <th><%= t "description" %></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @suggests.each do |suggest| %>
              <tr>
                <th><%= suggest.name %></th>
                <% if !suggest.image.nil? %>
                  <th><%= image_tag suggest.image %></th>
                <% else %>
                  <th><%= t "no_image" %></th>
                <% end %>
                <th><%= suggest.description %></th>
                <th>
                  <% if suggest.status? %>
                    <%= link_to new_admin_product_path(product_suggest: suggest.id), title: t("add") do %>
                      <span class="glyphicon glyphicon-pencil"><%= t "add" %></span>
                    <% end %>
                  <% else %>
                    <span><%= t "added" %></span>
                  <% end %>
                </th>
                <th>
                  <%= link_to t("delete"), admin_suggest_path(suggest.id),
                    method: :delete, class: "btn btn-danger btn-sm",
                    data: {confirm: t("admin.confirm_del")} %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>